# Generated by Django 3.0.4 on 2020-03-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_address', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=1, max_digits=3)),
                ('salad', models.PositiveSmallIntegerField()),
                ('bacon', models.PositiveSmallIntegerField()),
                ('meat', models.PositiveSmallIntegerField()),
                ('cheese', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
