# Generated by Django 3.0.4 on 2020-03-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('fastest', 'Fastest'), ('cheapest', 'cheapest')], default='fastest', max_length=255),
        ),
    ]
